- hosts: RHEL
  become: true
  tasks: 

   - name: get GPG-key
     get_url:
       url: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
       dest: /home/ec2-user

   - name: install EPEL repo
     yum:
       name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
       state: latest
       enablerepo: "epel"
     register: result
     until: result is succeeded
     retries: 5
     delay: 10


   - name: Updating yum cache
     yum:
       update_cache: yes
       state: present 
   
   - name: installing packages
     yum:
       name: "{{ item }}"
       state: latest
     loop:
          - python3
          - net-tools
          - vim
          - wget
          - telnet
          - epel-release
          - htop
          - chrony

   - name: ensure chronyd(ntp) is running 
     service:
       name: chronyd
       state: started
       enabled: yes